# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_weixininfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixininfo',
            name='type',
            field=models.CharField(max_length=2),
        ),
    ]
