# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20160629_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixininfo',
            name='type',
            field=models.CharField(choices=[('0', '订阅号'), ('1', '服务号'), ('2', '企业号')], default='0', max_length=2),
        ),
    ]
