# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20160629_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('register_time', models.DateTimeField(verbose_name='注册时间')),
                ('last_login_time', models.DateTimeField(verbose_name='最后登陆时间')),
            ],
        ),
        migrations.AddField(
            model_name='weixininfo',
            name='token',
            field=models.CharField(default='qweixin', max_length=100),
        ),
        migrations.AlterField(
            model_name='weixininfo',
            name='appid',
            field=models.CharField(max_length=200, verbose_name='Appid'),
        ),
        migrations.AlterField(
            model_name='weixininfo',
            name='appkey',
            field=models.CharField(max_length=200, verbose_name='Appkey'),
        ),
        migrations.AlterField(
            model_name='weixininfo',
            name='name',
            field=models.CharField(max_length=200, verbose_name='微信名'),
        ),
        migrations.AlterField(
            model_name='weixininfo',
            name='originid',
            field=models.CharField(max_length=200, verbose_name='原始id'),
        ),
        migrations.AlterField(
            model_name='weixininfo',
            name='type',
            field=models.CharField(choices=[('0', '订阅号'), ('1', '服务号'), ('2', '企业号')], default='0', max_length=2, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='weixininfo',
            name='uid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Home.User'),
        ),
    ]
