# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20160630_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixininfo',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.User'),
        ),
    ]
