# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0008_auto_20160630_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='标识')),
                ('title', models.CharField(max_length=200, verbose_name='中文名')),
                ('description', models.TextField(verbose_name='插件描述')),
                ('status', models.CharField(choices=[('0', '模糊'), ('1', '精确')], max_length=2, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='关键词')),
                ('type', models.CharField(choices=[('0', '模糊'), ('1', '精确')], default='0', max_length=2, verbose_name='类别')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddonsBase.Addon')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.WeixinInfo')),
            ],
        ),
    ]
