# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddonsBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='status',
            field=models.CharField(choices=[('0', '关闭'), ('1', '开启')], max_length=2, verbose_name='状态'),
        ),
    ]
